# Generated by Django 4.2.11 on 2024-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumax_account', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
