# Generated by Django 4.2.7 on 2024-06-01 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumax_account', '0003_alter_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="ID는 알파벳 대소문자나 숫자, '_'만을 포함하는 4~20자의 문자열이어야 합니다.", regex='^[a-zA-Z0-9_]{4,20}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='닉네임은 영문, 숫자, 한글로 이루어진 2~10자의 문자열이어야 합니다.', regex='^[\\u3131-\\u318E\\uAC00-\\uD7A3a-zA-Z0-9]{2,10}$')]),
        ),
    ]
