name: Django CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Decode Firebase config and save to file
      run: |
        mkdir -p ../  # 상위 디렉토리를 만듭니다
        echo $FIREBASE_CONFIG_JSON | base64 --decode > ../edumaxprod-5fa4e-firebase-adminsdk-rcs4p-f3aba62466.json
      env:
        FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}

    - name: Run Tests
      run: |
        pytest --ds=config.settings.local
