name: Django CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]  # Python 버전을 3.10으로 설정

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 코드 체크아웃 액션

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3  # Python 설정 액션
      with:
        python-version: ${{ matrix.python-version }}  # 매트릭스에서 Python 버전을 가져옴

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip  # pip 업그레이드
        pip install -r requirements.txt  # 의존성 설치

    - name: Run Tests
      run: |
        pytest --ds=config.settings.local  # 테스트 실행
